apiVersion: v1
kind: Service
metadata:
  name: nexus-nodeport
spec:
  selector:
    app: nexus
  type: NodePort
  ports:
  - name: httpport
    protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30600
  - name: nexus-docker
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30700
  - name: nexus-docker-group
    protocol: TCP
    port: 5001
    targetPort: 5001
    nodePort: 30701
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  labels:
    name: nexus
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      securityContext:
        fsGroup: 1000 
        runAsUser: 0
      containers:
      - name: nexus
        image: sonatype/nexus3:latest
        imagePullPolicy: Always
        ports:
        - name: httpport
          containerPort: 8081
        - name: dockerport
          containerPort: 5000
        - name: dockerport1
          containerPort: 5001
        volumeMounts:
        - name: nexus-storage
          mountPath: '/nexus-data'
      volumes:
      - name: nexus-storage
        hostPath:
          path: '/data/nexus-data'
